--liquibase formatted sql

--author Igor Verbitskiy

--task TASK-001

--changeset 1:1

CREATE TABLE IF NOT EXISTS CRYPTO_CURRENCY
(
    ID BIGSERIAL,
    SYMBOL VARCHAR NOT NULL,
    CURRENCY_ID INT NOT NULL,
    PRICE_USD DECIMAL NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER_NOTICE
(
    ID BIGSERIAL,
    USERNAME VARCHAR NOT NULL,
    PRICE_USD DECIMAL NOT NULL,
    CRYPTO_CURRENCY_ID BIGINT,
    FOREIGN KEY (CRYPTO_CURRENCY_ID) REFERENCES CRYPTO_CURRENCY (ID),
    PRIMARY KEY (ID)
);